### ISSUE TITLE
[이슈 목록 화면] 이슈 목록 컴포넌트 구현

### ISSUE THREAD

**Issue by sang-gyeong** [boostcamp-2020/IssueTracker-28#2]
### 예상 화면
<img width="581" alt="스크린샷 2020-10-27 오전 11 35 10" src="https://user-images.githubusercontent.com/60839959/97250119-9ca98780-1848-11eb-8e18-5579140f6f41.png">

### 기능
- 오픈상태의 이슈 목록을 보여준다.

### 요구사항
- ➊ 이슈 목록을 보여준다.
- 오픈 상태의 이슈만 보여주는 게 기본 상태이다.
- 제목, 마일스톤, 레이블, 이슈 번호, 이슈 작성 시간, 작성자, 담당자를 표시한다. 해당 값이 없으면 보여주지 않아도 된다.
- 이슈 제목을 선택하면 선택한 이슈에 대한 상세 화면 페이지로 이동한다.

**Comment by johnyejin** [comment]
## Week1 Day3 Todo
### 어제 했던 브랜치에서 작업
- [x] package.json -> styled-components 한개 지우기
- [x] [yejin] style.js 수정
- [x] [yejin] svg -> github lib 사용해서 수정
- [x] [sanggyeong] filter 팝업 구현
- [x] issueHeader, IssueList 합치기

### 새로운 브랜치에서 작업
